# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  fireteamreport:
    image: fireteamreport
    build:
      context: .
      dockerfile: FireteamReport/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5274:5274
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
